import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { whatsappUrl } from "./getInTouch";
export default function Footer() {
    return (_jsx("footer", { className: "relative bottom-0  text-white py-5  px-4", style: {
            backgroundImage: `url(/asset/landing/art-tools-mini.png)`,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
        }, children: _jsxs("div", { className: "container opacity-90 p-10 bg-gray-900 rounded-md mx-auto grid grid-cols-1 md:grid-cols-3 gap-8", children: [_jsxs("div", { className: "flex flex-col", children: [_jsx("h3", { className: "text-2xl font-semibold text-blue-400 mb-4", children: "JaTTo Constructions" }), _jsx("p", { className: "mb-4", children: "Aluminum fabrication and general contracting company." }), _jsxs("p", { children: ["\u00A9 ", new Date().getFullYear(), " JaTTo Constructions. All rights reserved."] })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("h3", { className: "text-xl font-semibold text-blue-400 mb-4", children: "Quick Links" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { children: _jsx(Link, { to: "/about", className: "hover:underline", children: "About Us" }) }), _jsx("li", { children: _jsx(Link, { to: "/", className: "hover:underline", children: "Our Services" }) }), _jsx("li", { children: _jsx(Link, { to: "gallery", className: "hover:underline", children: "Projects" }) })] })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("h3", { className: "text-xl font-semibold text-blue-400 mb-4", children: "Contact Us" }), _jsx("p", { className: "mb-2", children: "Phone: +234 812 7967 257" }), _jsx("p", { className: "mb-2", children: "Email: j.j.jatto@gmail.com" }), _jsxs("p", { className: "mb-2", children: [" ", _jsx("a", { href: whatsappUrl, target: "_blank", children: "WhatsApp" })] }), _jsx("p", { className: "mb-4", children: "Location: One Touch Aluminum opposite FGC Jos." }), _jsxs("p", { className: "text-xs text-right font-semibold text-blue-400 mb-4", children: ["Powered by ", _jsx("a", { href: 'https://joshua-jatto.github.io/JLABS-Portfolio/', target: '_blank', children: "JLABS" })] })] })] }) }));
}
