import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function OurServices() {
    return (_jsx("section", { className: " text-white py-8 transition-all ease-in duration-300", children: _jsxs("div", { className: " container mx-auto px-4 grid md:grid-cols-2 gap-8", children: [_jsxs("div", { className: " relative bg-gray-800 bg-opacity-70 rounded-lg shadow-lg p-8 transition-all ease-in", style: {
                        backgroundImage: `url(/asset/servicesBkg/stircase_handrail.jpg)`,
                        backgroundSize: 'cover',
                        backgroundPosition: 'center',
                    }, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-b from-gray-900 via-transparent to-gray-900 opacity-70 rounded-lg" }), _jsxs("div", { className: "relative z-10", children: [_jsx("h1", { className: "text-3xl font-bold mb-6 text-gray-100 ring ring-white p-3 w-auto", children: "Our Services" }), _jsxs("ul", { className: "space-y-4 text-lg", children: [_jsx("li", { className: "text-2xl ", children: "Aluminium Fabrications" }), _jsx("li", { className: "text-2xl ", children: "Stainless Steel Installation" }), _jsx("li", { className: "text-2xl ", children: "Suspended Ceiling Installation" }), _jsx("li", { className: "text-2xl ", children: "Structural Cladding" }), _jsx("li", { className: "text-2xl ", children: "General Contracting and Consultations" })] })] })] }), _jsxs("div", { className: "relative bg-gray-800 bg-opacity-70 rounded-lg shadow-lg p-8 transition-all ease-in", style: {
                        backgroundImage: `url(/asset/servicesBkg/casement_fabrication.jpg)`,
                        backgroundSize: "cover",
                        backgroundPosition: "center",
                    }, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-b from-gray-900 via-transparent to-gray-900 opacity-70 rounded-lg" }), _jsxs("div", { className: "relative z-10 ", children: [_jsx("h3", { className: "text-3xl font-bold mb-6 text-gray-100 ring ring-white p-3 w-auto", children: "Customization Options" }), _jsxs("ul", { className: "space-y-4 text-lg", children: [_jsx("li", { className: "text-2xl ", children: "Cutting wall / Frameless windows" }), _jsx("li", { className: "text-2xl ", children: "Double-hung casement" }), _jsx("li", { className: "text-2xl ", children: "Single-hung casement" }), _jsx("li", { className: "text-2xl ", children: "Sliding windows" }), _jsx("li", { className: "text-2xl ", children: "Projected windows" }), _jsx("li", { className: "text-2xl ", children: "Arches, Curves finishing, and more..." })] })] })] })] }) }));
}
